#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-fastutil
Version  : 7.0.13
Release  : 1
URL      : https://github.com/vigna/fastutil/archive/7.0.13.tar.gz
Source0  : https://github.com/vigna/fastutil/archive/7.0.13.tar.gz
Source1  : https://repo1.maven.org/maven2/it/unimi/dsi/fastutil/7.0.13/fastutil-7.0.13.jar
Source2  : https://repo1.maven.org/maven2/it/unimi/dsi/fastutil/7.0.13/fastutil-7.0.13.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-fastutil-data = %{version}-%{release}

%description
Welcome to fastutil.
--------------------
[fastutil](http://fastutil.di.unimi.it/) is a collection of type-specific
Java classes that extend the Java Collections Framework by providing
several containers, such as maps, sets, lists and prority queues,
implementing the interfaces of the java.util package; it provides also big
(64-bit) arrays, sets and lists, and fast, practical I/O classes for
binary and text files.

%package data
Summary: data components for the mvn-fastutil package.
Group: Data

%description data
data components for the mvn-fastutil package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/it/unimi/dsi/fastutil/7.0.13
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/it/unimi/dsi/fastutil/7.0.13/fastutil-7.0.13.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/it/unimi/dsi/fastutil/7.0.13
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/it/unimi/dsi/fastutil/7.0.13/fastutil-7.0.13.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/it/unimi/dsi/fastutil/7.0.13/fastutil-7.0.13.jar
/usr/share/java/.m2/repository/it/unimi/dsi/fastutil/7.0.13/fastutil-7.0.13.pom
